project_id = "bloodconnectindia-disposable-ci"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]

[db]
port = 54322
shadow_port = 54320

[auth]
enabled = true
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["http://127.0.0.1:3000/pages/admin-reset-password.html"]

[inbucket]
enabled = true
port = 54324

[edge_runtime]
enabled = true
policy = "per_worker"
